# ---- Site basics ----
title: "Games Lab — Events & Experiences"
description: "Immersive events, party games, and social experiences."
url: https://gameslabbangalore-maker.github.io                # keep empty for GitHub Pages project sites
baseurl: /website            # we will use {{ '/path' | relative_url }} everywhere
theme: null

# SEO: auto-generate /sitemap.xml on each build (GitHub Pages supports this plugin)
plugins:
  - jekyll-sitemap

# ---- Build & Markdown ----
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Kolkata
future: true           # show upcoming-dated content (safe for collections)

# ---- Sass (SCSS) ----
sass:
  sass_dir: assets/css
  style: compressed

# ---- Collections ----
collections:
  events:
    output: true
    permalink: /events/:slug/

# ---- Defaults (so you write less front matter) ----
defaults:
  # All pages get the generic layout unless overridden
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

  # Event pages default to the event layout
  - scope:
      path: ""
      type: "events"
    values:
      layout: event

  # The homepage (index) will override to layout: home in its own front matter

# ---- Plugins (GitHub Pages–whitelisted) ----
# These are safe & optional, but recommended.
plugins:
  - jekyll-seo-tag    # SEO meta (we'll include it in head.html)
  - jekyll-sitemap    # /sitemap.xml for search engines
  - jekyll-feed       # /feed.xml (nice-to-have)

# ---- Exclusions to keep the output lean ----
exclude:
  - node_modules/
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - .github/
  - .vscode/
  - .idea/

# ---- Kramdown (Markdown engine) tweaks ----
kramdown:
  input: GFM
  hard_wrap: false

collections:
  events:
    output: true
    permalink: /events/:slug/

defaults:
  - scope: { path: "", type: events }
    values:
      layout: event        # use our event layout for all event files
      sitemap: true
